import { $, save, addPoints, navigate } from '../app.js';
function pct(v,max){return Math.min(100,Math.round((v/max)*100));}
export function renderHome(root,state){
 const today=state.todos.filter(t=>t.date==='today'), tomorrow=state.todos.filter(t=>t.date==='tomorrow');
 root.innerHTML=`<section class="card"><p class="muted">Bonjour Margot</p><div class="row"><div><div class="big">Niveau ${state.level}</div><span class="pill">${state.points} points</span></div><button class="btn" id="surprise">Surprise culture</button></div></section>
 <h2 class="sectionTitle">Inspirations</h2><div class="grid grid2"><button class="card soft" id="anti">🔒 Anti-scroll</button><button class="card soft" data-go="mood">🧠 Mood</button><button class="card soft" id="softTask">🌿 Tâche douce</button><button class="card soft" data-go="culture">🎬 Surprise culture</button></div>
 <h2 class="sectionTitle">Récapitulatif complet</h2><section class="grid grid2"><div class="card"><b>Points</b><div class="big">${state.points}</div></div><div class="card"><b>Sport</b><div>${state.sport.week}/4 semaine</div></div><div class="card"><b>Skincare</b><div>${state.daily.skincare?1:0}/7</div></div><div class="card"><b>Pas</b><div>${state.steps}/10k</div></div><div class="card"><b>To-do</b><div>${today.filter(t=>!t.done).length} aujourd’hui</div></div><div class="card"><b>Stretching</b><div>${state.sport.stretching}/7</div></div><div class="card"><b>Calories</b><div>${state.calories}</div></div><div class="card"><b>Protéines</b><div>${state.proteins}g</div></div></section>
 <h2 class="sectionTitle">Quotidien</h2><section class="card list"><label class="item"><input type="checkbox" data-daily="skincare" ${state.daily.skincare?'checked':''}> Skincare</label><label class="item"><input type="checkbox" data-daily="stretching" ${state.daily.stretching?'checked':''}> Stretching</label><label class="item"><input type="checkbox" data-daily="water" ${state.daily.water?'checked':''}> 2L d’eau</label><div><div class="row"><b>Pas</b><span>${state.steps}/10000</span></div><div class="progress"><div class="bar" style="width:${pct(state.steps,10000)}%"></div></div><input class="input" id="steps" type="number" value="${state.steps}" min="0"></div></section>
 <h2 class="sectionTitle">Agenda aujourd’hui et demain</h2><section class="calBox">${['today','tomorrow'].map(d=>`<div class="card"><b>${d==='today'?'Aujourd’hui':'Demain'}</b>${state.agenda.filter(a=>a.day===d).map(a=>`<p>${a.time} · ${a.title}</p>`).join('')||'<p class="muted">Rien de prévu</p>'}</div>`).join('')}</section>`;
 root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go)); root.querySelector('#softTask').onclick=()=>alert('Tâche douce : ranger un seul petit coin pendant 7 minutes.'); root.querySelector('#surprise').onclick=()=>navigate('culture'); root.querySelectorAll('[data-daily]').forEach(c=>c.onchange=e=>{state.daily[e.target.dataset.daily]=e.target.checked; if(e.target.checked)addPoints(state,15); save(state);renderHome(root,state)}); $('#steps').onchange=e=>{state.steps=+e.target.value;save(state);renderHome(root,state)};
}
